### 开发环境
server:
  port: 63
spring:
  application:
    name: admin
  main:
    allow-bean-definition-overriding: true  # 解决Bean重复定义问题
  ## 数据库数据源配置
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://10.0.117.216:3306/simulation?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useAffectedRows=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://10.0.117.216:3306/simulation?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useAffectedRows=true&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    druid:
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: root1.
        allow:
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      filters: stat, wall
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 5000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 20000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ## redis配置
  redis:
    password:
    sentinel:
      master: mymaster
      nodes: 10.0.117.216:26379
    database: 1
    timeout: 6000

## Mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml  # 配置文件路径

## Pagehelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: false
  params: count=countSql

## Log
logging:
  config: classpath:logback-spring.xml
  file:
    path: ./logger/simulation-service-admin
  level:
    com.iqilu.*: debug

# 消息开关
message_on_off: false

# 客户端用户地址 - 通过用户电话获取用户ID
client_get_user_id_link: "https://app-auth.iqilu.com/service/member/byphone"
# 客户端用户地址 - 根据ID获取用户信息
client_get_user_info_link: "https://app-auth.iqilu.com/service/member/byids"
# 客户端用户地址 - 消息推送到一县一端APP
message_push: "https://app-auth.iqilu.com/service/message/add"

# 后台 - 根据用户账号获取用户信息
admin_get_user_info: "http://appopen.cq.qiludev.com/user/adminUserList"

## 后台页面地址
admin_web_link: "http://192.168.10.72/page_admin/index.html"